[2024-08-08T08:11:15.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T08:11:15.643+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [queued]>
[2024-08-08T08:11:15.649+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [queued]>
[2024-08-08T08:11:15.649+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2024-08-08T08:11:15.660+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_11str> on 2024-08-08 04:00:00+00:00
[2024-08-08T08:11:15.667+0000] {standard_task_runner.py:63} INFO - Started process 691 to run task
[2024-08-08T08:11:15.671+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_11str', 'update_11str', 'scheduled__2024-08-08T04:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/str11_batch.py', '--cfg-path', '/tmp/tmpxjp43fqv']
[2024-08-08T08:11:15.673+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask update_11str
[2024-08-08T08:11:15.714+0000] {task_command.py:426} INFO - Running <TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [running]> on host b4c0c56d2c27
[2024-08-08T08:11:15.780+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_11str' AIRFLOW_CTX_TASK_ID='update_11str' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T04:00:00+00:00'
[2024-08-08T08:11:15.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T08:11:16.509+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-08-08T08:11:16.532+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:11:16.612+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2024-08-08T08:11:16.680+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-08-08T08:11:16.770+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:11:17.013+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:11:17.073+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2024-08-08T08:11:17.075+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T08:11:17.076+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/str11_batch.py", line 28, in update_11str
    price, prices_id, deleted = extract_price_11str()
  File "/opt/airflow/dags/utils/crawl_11str.py", line 103, in extract_price_11str
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
[2024-08-08T08:11:17.082+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_11str, task_id=update_11str, execution_date=20240808T040000, start_date=20240808T081115, end_date=20240808T081117
[2024-08-08T08:11:17.092+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task update_11str (WebDriver.__init__() got an unexpected keyword argument 'executable_path'; 691)
[2024-08-08T08:11:17.124+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-08T08:11:17.144+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T08:11:17.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
