[2024-08-12T06:18:52.529+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T06:18:52.552+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12T06:18:52.559+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12T06:18:52.559+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-08-12T06:18:52.570+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_11str> on 2024-08-12 00:00:00+00:00
[2024-08-12T06:18:52.579+0000] {standard_task_runner.py:63} INFO - Started process 188846 to run task
[2024-08-12T06:18:52.582+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_11str', 'update_11str', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/str11_batch.py', '--cfg-path', '/tmp/tmpdetw311_']
[2024-08-12T06:18:52.585+0000] {standard_task_runner.py:91} INFO - Job 184: Subtask update_11str
[2024-08-12T06:18:52.630+0000] {task_command.py:426} INFO - Running <TaskInstance: update_11str.update_11str scheduled__2024-08-12T00:00:00+00:00 [running]> on host bcc9fe6b3d78
[2024-08-12T06:18:52.702+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_11str' AIRFLOW_CTX_TASK_ID='update_11str' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T00:00:00+00:00'
[2024-08-12T06:18:52.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T06:18:52.981+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-08-12T06:18:53.007+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-12T06:18:53.302+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2024-08-12T06:18:53.459+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-08-12T06:18:53.853+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-12T06:18:54.231+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-12T06:18:54.404+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2024-08-12T06:18:54.422+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T06:18:54.423+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/str11_batch.py", line 28, in update_11str
    price, prices_id, deleted = extract_price_11str()
  File "/opt/airflow/dags/utils/crawl_11str.py", line 103, in extract_price_11str
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2024-08-12T06:18:54.438+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_11str, task_id=update_11str, execution_date=20240812T000000, start_date=20240812T061852, end_date=20240812T061854
[2024-08-12T06:18:54.460+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 184 for task update_11str (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
; 188846)
[2024-08-12T06:18:54.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-12T06:18:54.570+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T06:18:54.577+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
