[2024-08-08T06:00:13.741+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T06:00:13.759+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-08T06:00:13.765+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-08T06:00:13.766+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-08-08T06:00:13.777+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_11str> on 2024-08-08 00:00:00+00:00
[2024-08-08T06:00:13.785+0000] {standard_task_runner.py:63} INFO - Started process 135 to run task
[2024-08-08T06:00:13.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_11str', 'update_11str', 'scheduled__2024-08-08T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/str11_batch.py', '--cfg-path', '/tmp/tmprvm5obew']
[2024-08-08T06:00:13.790+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask update_11str
[2024-08-08T06:00:13.832+0000] {task_command.py:426} INFO - Running <TaskInstance: update_11str.update_11str scheduled__2024-08-08T00:00:00+00:00 [running]> on host 9acd193613ba
[2024-08-08T06:00:13.899+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_11str' AIRFLOW_CTX_TASK_ID='update_11str' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T00:00:00+00:00'
[2024-08-08T06:00:13.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T06:00:14.673+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-08-08T06:00:14.696+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T06:00:14.814+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2024-08-08T06:00:14.880+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-08-08T06:00:14.978+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T06:00:15.198+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T06:00:15.261+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2024-08-08T06:00:15.276+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T06:00:15.276+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/str11_batch.py", line 28, in update_11str
    price, prices_id, deleted = extract_price_11str()
  File "/opt/airflow/dags/utils/crawl_11str.py", line 102, in extract_price_11str
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2024-08-08T06:00:15.287+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_11str, task_id=update_11str, execution_date=20240808T000000, start_date=20240808T060013, end_date=20240808T060015
[2024-08-08T06:00:15.299+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task update_11str (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
; 135)
[2024-08-08T06:00:15.322+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-08T06:00:15.372+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T06:00:15.379+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
