[2024-08-07T20:00:02.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T20:00:02.499+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_coupang.update_coupang scheduled__2024-08-07T16:00:00+00:00 [queued]>
[2024-08-07T20:00:02.505+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_coupang.update_coupang scheduled__2024-08-07T16:00:00+00:00 [queued]>
[2024-08-07T20:00:02.506+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-08-07T20:00:02.517+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_coupang> on 2024-08-07 16:00:00+00:00
[2024-08-07T20:00:02.524+0000] {standard_task_runner.py:63} INFO - Started process 22453 to run task
[2024-08-07T20:00:02.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_coupang', 'update_coupang', 'scheduled__2024-08-07T16:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/coupang_batch.py', '--cfg-path', '/tmp/tmp66g78z4g']
[2024-08-07T20:00:02.528+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask update_coupang
[2024-08-07T20:00:02.569+0000] {task_command.py:426} INFO - Running <TaskInstance: update_coupang.update_coupang scheduled__2024-08-07T16:00:00+00:00 [running]> on host 36f576e8f7f1
[2024-08-07T20:00:02.632+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_coupang' AIRFLOW_CTX_TASK_ID='update_coupang' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T16:00:00+00:00'
[2024-08-07T20:00:02.633+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T20:00:02.634+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T20:00:02.634+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coupang_batch.py", line 98, in coupang_info_manual
    with open('/data/jw_vol/airflow/dags/mongo.yaml') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jw_vol/airflow/dags/mongo.yaml'
[2024-08-07T20:00:02.640+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_coupang, task_id=update_coupang, execution_date=20240807T160000, start_date=20240807T200002, end_date=20240807T200002
[2024-08-07T20:00:02.649+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task update_coupang ([Errno 2] No such file or directory: '/data/jw_vol/airflow/dags/mongo.yaml'; 22453)
[2024-08-07T20:00:02.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T20:00:02.682+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T20:00:02.685+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
