[2024-08-12T20:00:02.753+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T20:00:02.774+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-12T16:00:00+00:00 [queued]>
[2024-08-12T20:00:02.782+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-12T16:00:00+00:00 [queued]>
[2024-08-12T20:00:02.782+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-08-12T20:00:02.794+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_11str> on 2024-08-12 16:00:00+00:00
[2024-08-12T20:00:02.803+0000] {standard_task_runner.py:63} INFO - Started process 23258 to run task
[2024-08-12T20:00:02.809+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_11str', 'update_11str', 'scheduled__2024-08-12T16:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/str11_batch.py', '--cfg-path', '/tmp/tmphogm1npm']
[2024-08-12T20:00:02.812+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask update_11str
[2024-08-12T20:00:02.855+0000] {task_command.py:426} INFO - Running <TaskInstance: update_11str.update_11str scheduled__2024-08-12T16:00:00+00:00 [running]> on host 8672f9a318d9
[2024-08-12T20:00:02.930+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_11str' AIRFLOW_CTX_TASK_ID='update_11str' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T16:00:00+00:00'
[2024-08-12T20:00:02.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T20:00:03.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T20:00:03.363+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/str11_batch.py", line 28, in update_11str
    price, prices_id, deleted = extract_price_11str()
  File "/opt/airflow/dags/utils/crawl_11str.py", line 108, in extract_price_11str
    driver = webdriver.Chrome(service=service, options=chrome_options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to locate or obtain driver for {options.capabilities['browserName']}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2024-08-12T20:00:03.372+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_11str, task_id=update_11str, execution_date=20240812T160000, start_date=20240812T200002, end_date=20240812T200003
[2024-08-12T20:00:03.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 214 for task update_11str (Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
; 23258)
[2024-08-12T20:00:03.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-12T20:00:03.462+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T20:00:03.467+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
